const rolesArray = ['Machine Learning Engineer',
'Data Scientist',
'AI Research Scientist',
'Computer Vision Engineer',
'Natural Language Processing (NLP) Engineer',
'Robotics Engineer',
'Deep Learning Engineer',
'AI Ethics Specialist',
'Business Intelligence Analyst',
'Cloud Solutions Architect',
'AI Product Manager',
'IoT (Internet of Things) Developer',
'AI Software Developer',
'Quantum Computing Scientist',
'Cybersecurity Analyst',
'AR (Augmented Reality) / VR (Virtual Reality) Developer',
'Blockchain Developer',
'Big Data Engineer',
'Autonomous Vehicle Engineer',
'Speech Recognition Engineer',
'Conversational AI Developer',
'DevOps Engineer',
'Full Stack Developer',
'UI/UX Designer',
'Game Developer',
'Mobile App Developer',
'Network Engineer',
'System Administrator',
'Quality Assurance Engineer',
'Technical Writer',
'IT Project Manager',
'Database Administrator',
'Network Security Engineer',
'Frontend Developer',
'Backend Developer',
'Systems Analyst',
'IT Consultant',
'Computer Hardware Engineer',
'Embedded Systems Engineer',
'UI/UX Researcher',
'Digital Marketing Specialist',
'Social Media Manager',
'Content Strategist',
'User Acquisition Specialist',
'SEO Specialist',
'E-commerce Manager',
'Business Analyst',
'Project Coordinator',
'Customer Success Manager',
'Product Owner',
'Sales Engineer',
'Cloud Support Engineer',
'Human Resources (HR) Specialist',
'Legal Tech Analyst',
'Health Informatics Specialist',
'Telecommunications Engineer',
'Renewable Energy Engineer',
'Environmental Scientist',
'Supply Chain Analyst',
'Logistics Coordinator',
'Financial Analyst',
'Cryptocurrency Analyst',
'Virtual Assistant Developer',
'Educational Technology Specialist',
'Fitness Technology Developer',
'Space Exploration Scientist'];
  
  export default rolesArray;
  