const TechnicalSkillsArray = [
    'Python',
    'R',
    'Java',
    'C++',
    'JavaScript',
    'SQL',
    'Matlab',
    'Scala',
    'Ruby',
    'Go',
    'Swift',
    'Kotlin',
    'TensorFlow',
    'PyTorch',
    'Scikit-learn',
    'Pandas',
    'NumPy',
    'Deep Learning',
    'Machine Learning',
    'Data Science',
    'Natural Language Processing (NLP)',
    'Computer Vision',
    'Robotics',
    'Artificial Intelligence (AI)',
    'Ethical AI',
    'Business Intelligence',
    'Cloud Computing',
    'AWS',
    'Azure',
    'Google Cloud Platform (GCP)',
    'DevOps',
    'Docker',
    'Kubernetes',
    'Full Stack Development',
    'Frontend Development',
    'Backend Development',
    'UI/UX Design',
    'Game Development',
    'Mobile App Development',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Express.js',
    'Django',
    'Flask',
    'Spring Boot',
    'RESTful APIs',
    'GraphQL',
    'Blockchain',
    'Smart Contracts',
    'Big Data',
    'Hadoop',
    'Spark',
    'Apache Kafka',
    'NoSQL Databases',
    'MongoDB',
    'Cassandra',
    'Redis',
    'Cybersecurity',
    'Penetration Testing',
    'Network Security',
    'Cryptography',
    'Augmented Reality (AR)',
    'Virtual Reality (VR)',
    'ARKit',
    'ARCore',
    'Unity',
    'Unreal Engine',
    'Blockchain Development',
    'Smart Contracts',
    'Ethereum',
    'Solidity',
    'Cryptocurrency',
    'IoT (Internet of Things)',
    'Embedded Systems',
    'Microservices Architecture',
    'Serverless Computing',
    'Speech Recognition',
    'Conversational AI',
    'Chatbots',
    'Natural Language Understanding (NLU)',
    'Agile Methodology',
    'Scrum',
    'Kanban',
    'CI/CD',
    'Jenkins',
    'Git',
    'Bitbucket',
    'Jira',
    'UI/UX Research',
    'Digital Marketing',
    'SEO',
    'Content Marketing',
    'Social Media Management',
    'E-commerce',
    'Business Analysis',
    'Project Management',
    'Sales Engineering',
    'Customer Success Management',
    'Cloud Support',
    'Human Resources (HR) Management',
    'Legal Tech',
    'Health Informatics',
    'Telecommunications',
    'Renewable Energy',
    'Environmental Science',
    'Supply Chain Management',
    'Logistics',
    'Financial Analysis',
    'Virtual Assistance Development',
    'Educational Technology',
    'Fitness Technology',
    'Space Exploration',
    'Natural Language Generation (NLG)',
    'Reinforcement Learning',
    'Quantum Computing',
    'AR/VR Content Creation',
    '3D Modeling',
    'SwiftUI',
    'RxJS',
    'WebAssembly',
    'Microfrontend Architecture',
    'Cypress Testing',
    'Redux',
    'Firebase',
    'GraphQL Yoga',
    'Laravel',
    'Symfony',
    'ASP.NET Core',
    'Vue.js 3',
    'Sass',
    'LESS',
    'Webpack',
    'Jest',
    'Cucumber',
    'Test-Driven Development (TDD)',
    'Behavior-Driven Development (BDD)',
    'WebRTC',
    'Apache Flink',
    'RabbitMQ',
    'GraphQL Apollo Server',
    'OAuth',
    'JSON Web Tokens (JWT)',
    'WebSockets',
    'Zookeeper',
    'Azure DevOps',
    'GitHub Actions',
    'CI/CD Pipelines',
    'Serverless Framework',
    'GraphQL Nexus',
    'Apollo Client',
    'Tailwind CSS',
    'Material-UI',
    'Chakra UI',
    'Storybook',
    'Next.js',
    'Nuxt.js',
    'Gatsby',
    'Blender',
    'ARCore Depth API',
    'SnapKit',
    'MapReduce',
    'FlinkML',
    'Elasticsearch',
    'Apache NiFi',
    'DynamoDB',
    'PostgreSQL',
    'MySQL',
    'SQLite',
    'CouchDB',
    'Kibana',
    'Logstash',
    'Distributed Systems',
    'Blockchain Interoperability',
    'Chainlink',
    'DeFi (Decentralized Finance)',
    'IPFS',
    'Filecoin',
    'Hashgraph',
    'Tezos',
    'Quorum',
    'Zcash',
    'Decentralized Autonomous Organizations (DAOs)',
    'Stellar',
    'OpenCV',
    'Natural Language Generation (NLG)',
    'Virtual Private Networks (VPNs)',
    'WebAssembly',
    'Microservices Orchestration',
    'Knative',
    'Ambient Computing',
    'Edge Computing',
    'Quantum Machine Learning',
    'Bioinformatics',
    'Clinical Informatics',
    'Biostatistics',
    'Environmental Modeling',
    'Renewable Energy Grid Integration',
    'Climate Modeling',
    'Green Building Design',
    'Waste-to-Energy Technologies',
    'Hydroponics',
    'Vertical Farming',
    'Genome Sequencing',
    'Telehealth Technologies',
    'Medical Imaging Processing',
    'Biomechanics',
    'Pharmaceutical Manufacturing Technologies',
    'Augmented Reality in Healthcare',
    'Remote Patient Monitoring',
    'Nanotechnology',
    'Smart Grid Technologies',
    'Sustainable Transportation Systems',
    'Circular Economy Technologies',
    'Carbon Capture and Storage (CCS)',
    'Life Cycle Assessment (LCA)',
    'Supply Chain Transparency Technologies',
    'TensorRT',
    'Apache Camel',
    'Reactive Programming',
    'Elastic Stack',
    'Log Shipping',
    'Kotlin Coroutines',
    'Adobe XD',
    'Sketch',
    'InVision',
    'Zeplin',
    'Adobe Illustrator',
    'Adobe Photoshop',
    'Adobe After Effects',
    'Blender 3D Animation',
    'Unity Shader Programming',
    'Three.js',
    'ARKit 4',
    'ARCore Cloud Anchors',
    'Oculus Rift',
    'Vive VR',
    'Hololens',
    'Microsoft Azure Kinect',
    'Spatial Audio Processing',
    'Neural Architecture Search (NAS)',
    'AutoML',
    'BERT (Bidirectional Encoder Representations from Transformers)',
    'BERT-based NLP Models',
    'BERT-based Text Classification',
    'Graph Neural Networks (GNN)',
    'XGBoost',
    'LightGBM',
    'CatBoost',
    'Transfer Learning',
    'Self-Supervised Learning',
    'Federated Learning',
    'Quantum Machine Learning',
    'Quantum Cryptography',
    'Quantum Key Distribution (QKD)',
    'Quantum Algorithms',
    'Quantum Annealing',
    'Quantum Supremacy',
    'Quantum Error Correction',
    'Quantum Teleportation',
    'Quantum Entanglement',
    'Quantum Information Theory',
    'Quantum Gate Model',
    'Quantum Walk',
    'Quantum Biology',
    'Digital Twins',
    'Zero Trust Security',
    'Homomorphic Encryption',
    'Explainable AI (XAI)',
    'Generative Adversarial Networks (GAN)',
    'Capsule Networks',
    'Recommender Systems',
    'A/B Testing',
    'Multivariate Testing',
    'Collaborative Filtering',
    'Content-Based Filtering',
    'Hybrid Recommender Systems',
    'Recurrent Neural Networks (RNN)',
    'Long Short-Term Memory (LSTM)',
    'Gated Recurrent Unit (GRU)',
    'BERT-based Question Answering',
    'Neuromorphic Computing',
    'VLSI Design',
    'Quantum Dot Cellular Automata (QCA)',
    'Fuzzy Logic Controllers',
    'Genetic Algorithms',
    'Ant Colony Optimization',
    'Simulated Annealing',
    'Swarm Intelligence',
    'Differential Evolution',
    'Artificial Life',
    'Evolutionary Robotics',
    'Neuroevolution',
    'Hyperparameter Optimization',
    'Automatic Differentiation',
    'Distributed Ledger Technology (DLT)',
    'Rust Programming Language',
    'TypeScript',
    'RxJava',
    'GraphQL Yoga',
    'Selenium WebDriver',
    'Cypress Testing Framework',
    'Katalon Studio',
    'Postman',
    'Mockito',
    'Jasmine Testing Framework',
    'Raspberry Pi Programming',
    'Arduino Programming',
    'Espruino',
    'Flutter Framework',
    'Dart Programming Language',
    'React Native',
    'Swift Programming Language',
    'Objective-C',
    'Ionic Framework',
    'Apache Kafka Streams',
    'Amazon Kinesis',
    'Apache Storm',
    'DataOps',
    'Data Governance',
    'Data Stewardship',
    'Data Mesh',
    'Digital Ethics',
    'Exponential Technologies',
    'Green IT',
    'Intelligent Process Automation (IPA)',
    'Internet of Behavior (IoB)',
    'Low-Code Development',
    'No-Code Development',
    'Quantum Internet',
    'Remote Sensing Technologies',
    'Robotic Process Automation (RPA)',
    'Social Robots',
    'Swarm Robotics',
    'Ubiquitous Computing',
    'Unsupervised Learning',
    'Voice User Interface (VUI) Design',
    'Experiential Technology',
    'Human Augmentation',
    'Human-Computer Interaction (HCI)',
    'Humanoid Robotics',
    'Ambient Intelligence',
    'Anthropomorphic Robotics',
    'Biohybrid Robots',
    'Brain-Machine Interface (BMI)',
    'Conversational UX Design',
    'Cognitive Computing',
    'Digital Assistants',
    'Emotion AI',
    'Exoskeletons',
    'Human-Robot Collaboration',
    'Intelligent Virtual Assistants',
    'Mind Uploading',
    'Neuralink Technology',
    'Robotic Surgery',
    'Soft Robotics',
    'Synthetic Biology',
    'Transhumanism',
    'Volumetric Displays',
    'Wireless Power Transfer (WPT)',
    'Zero-Emission Vehicles',
    'Smart Fabrics',
    'NeuroMarketing',
    'NeuroWare',
    'Neuromorphic Engineering',
    'Neuroinformatics',
    'NeuroLeadership',
    'Neuroscience of Creativity',
    'Psychoacoustics',
    'Psychometrics',
    'Psychophysics',
    'Social Neuroscience',
    'Quantum Psychology',
    'Affective Computing',
    'Cognitive Neuroscience',
    'Computational Neuroscience',
    'Developmental Neuroscience',
    'Neuroeconomics',
    'Neuroethics',
    'Neurogenetics',
    'Neuroimaging',
    'Neuroinformatics',
    'Neuro-Linguistic Programming (NLP)',
    'Neuromarketing',
    'Neuromorphic Engineering',
    'Neuropharmacology',
    'Neurophysiology',
    'Neuropsychiatry',
    'Neuropsychology',
    'Neurosociology',
    'Neurotechnology',
    'Neurotheology',
    'Rehabilitation Robotics',
    'Retinal Implants',
    'Robot-Assisted Surgery',
    'Smart Prosthetics',
    'Social Robotics',
    'Soft Exosuits',
    'Speech Synthesis',
    'Virtual Reality Therapy',
    'Vision Prosthetics',
    'Wearable Robotics',
    'WebXR',
    'XR Interaction Design',
    'XR Simulation',
    'Zero-Gravity Robotics'
  ];

  const uniqueTechnicalSkillsArray = Array.from(new Set(TechnicalSkillsArray));
  
  export default uniqueTechnicalSkillsArray;
  